resources_dir: "~/.local/share/aptos-keyless/current_setups"
jwk_issuers:
  - issuer_name: "https://accounts.google.com"
    issuer_jwk_url: "https://www.googleapis.com/oauth2/v3/certs"
  - issuer_name: "test.oidc.provider"
    issuer_jwk_url: "https://github.com/aptos-labs/aptos-core/raw/main/types/src/jwks/rsa/secure_test_jwk.json"
  - issuer_name: "test.federated.oidc.provider"
    issuer_jwk_url: "https://github.com/aptos-labs/aptos-core/raw/main/types/src/jwks/rsa/secure_test_jwk.json"
enable_test_provider: true
enable_federated_jwks: true
